name: safelane
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rive: ^0.11.3
  flutter_svg: ^2.0.7
  flutter_vector_icons: ^2.0.0
  google_maps_flutter: ^2.1.11
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  confetti: ^0.7.0
  awesome_snackbar_content: ^0.1.3
  http: ^0.13.5
  anim_search_bar: ^2.0.3
  icon_decoration: any
  pie_chart: ^5.3.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  google_maps_routes: ^1.1.2
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  conditional_builder_null_safety: ^0.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/RiveAssets/
  - assets/Images/
  
  fonts:
    - family: Sangu
      fonts:
        - asset: assets/Fonts/sangu-regular.ttf
    
    - family: HonestSky
      fonts:
        - asset: assets/Fonts/honestskypersonaluse-6ypd1.otf

    # - family: Intel
    #   fonts:
    #     - asset: assets/Fonts/Inter-Regular.ttf
    #     - asset: assets/Fonts/Inter-SemiBold.ttf
    #       weight: 600
    - family: Poppins
      fonts:
      - asset: assets/Fonts/Poppins-Medium.ttf
